/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

import Entities.User;
import Tools.ConnexionBDD;
import java.util.Date;
import javax.swing.JFrame;


/**
 *
 * @author nicol
 */
public class FrmInterfacePrincipaleMoniteur extends javax.swing.JFrame {

    static User unUser;
    //---- Pour les tests ----
    ConnexionBDD maCnx;
    // ----------------
    
    /**
     * Creates new form FrmInterfacePrincipaleMoniteur
     */
    public FrmInterfacePrincipaleMoniteur(User unUser) {
        this.unUser = unUser;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStatistiqueMoniteur = new javax.swing.JButton();
        btnModifierMesInfos1 = new javax.swing.JButton();
        btnAjouterUneLicence1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPlanningMoniteur = new javax.swing.JTable();
        lblTitre = new javax.swing.JLabel();
        lblSeDeconnecter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Auto NMN");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnStatistiqueMoniteur.setText("Statistiques");
        btnStatistiqueMoniteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatistiqueMoniteurActionPerformed(evt);
            }
        });

        btnModifierMesInfos1.setText("Modifier mes infos");
        btnModifierMesInfos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierMesInfos1ActionPerformed(evt);
            }
        });

        btnAjouterUneLicence1.setText("Ajouter une licence");
        btnAjouterUneLicence1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterUneLicence1ActionPerformed(evt);
            }
        });

        tblPlanningMoniteur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblPlanningMoniteur);

        lblTitre.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        lblTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitre.setText("Bienvenue");

        lblSeDeconnecter.setForeground(new java.awt.Color(0, 51, 255));
        lblSeDeconnecter.setText("Se déconnecter");
        lblSeDeconnecter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSeDeconnecter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSeDeconnecterMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnStatistiqueMoniteur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModifierMesInfos1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAjouterUneLicence1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSeDeconnecter)
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSeDeconnecter)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnModifierMesInfos1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAjouterUneLicence1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnStatistiqueMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStatistiqueMoniteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatistiqueMoniteurActionPerformed

    }//GEN-LAST:event_btnStatistiqueMoniteurActionPerformed

    private void btnModifierMesInfos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierMesInfos1ActionPerformed
        FrmModifierInfos frm = new FrmModifierInfos(unUser);
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btnModifierMesInfos1ActionPerformed

    private void btnAjouterUneLicence1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterUneLicence1ActionPerformed
        
    }//GEN-LAST:event_btnAjouterUneLicence1ActionPerformed

    private void lblSeDeconnecterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSeDeconnecterMouseClicked
        unUser = null;
        FrmConnexion frm = new FrmConnexion();
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_lblSeDeconnecterMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         //---- Pour les tests ----
        Date uneDate = new Date();
        unUser = new User(8, "Gnocchi", "Gwendoline", 1, uneDate, "", "75008", "Paris", "0104310779");
        maCnx = new ConnexionBDD();
        // ----------------
        
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        lblTitre.setText("Bienvenue " + unUser.getPrenom());
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInterfacePrincipaleMoniteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInterfacePrincipaleMoniteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInterfacePrincipaleMoniteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInterfacePrincipaleMoniteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInterfacePrincipaleMoniteur(unUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouterUneLicence1;
    private javax.swing.JButton btnModifierMesInfos1;
    private javax.swing.JButton btnStatistiqueMoniteur;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSeDeconnecter;
    private javax.swing.JLabel lblTitre;
    private javax.swing.JTable tblPlanningMoniteur;
    // End of variables declaration//GEN-END:variables
}
