/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

import Controlers.CtrlVehicule;
import Controlers.CtrlMoniteur;
import Controlers.CtrlPlanning;
import Entities.Moniteur;
import Entities.Vehicule;
import Tools.ConnexionBDD;
import java.util.ArrayList;
import java.util.Date;
/**
 *
 * @author Poste de travail
 */
public class FrmReserverLeçon extends javax.swing.JFrame {

    private ConnexionBDD cnx;
    private CtrlVehicule ctrlV;
    private CtrlMoniteur ctrlM;
    private CtrlPlanning ctrlP;
    
    private ArrayList<Vehicule> listeVehicules;
    private ArrayList<Moniteur> listeMoniteurs;
    
    /**
     * Creates new form FrmReserverLeçon
     */
    public FrmReserverLeçon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReserver = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblHeures = new javax.swing.JLabel();
        lblCatV = new javax.swing.JLabel();
        cboHeures = new javax.swing.JComboBox<>();
        cboCategorieVehicule = new javax.swing.JComboBox<>();
        lblMoniteurs = new javax.swing.JLabel();
        cboMoniteurs = new javax.swing.JComboBox<>();
        lblVehicules = new javax.swing.JLabel();
        cboVehicules = new javax.swing.JComboBox<>();
        btnReserver = new javax.swing.JButton();
        dcDateLeçon = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(550, 350));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblReserver.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblReserver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReserver.setText("Réserver une leçon");

        lblDate.setText("Date :");

        lblHeures.setText("Heures disponibles :");

        lblCatV.setText("Type de véhicule :");

        cboCategorieVehicule.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboCategorieVehiculeItemStateChanged(evt);
            }
        });

        lblMoniteurs.setText("Moniteurs disponibles :");

        lblVehicules.setText("Véhicules disponibles :");

        btnReserver.setText("Réserver");

        dcDateLeçon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dcDateLeçonMouseClicked(evt);
            }
        });
        dcDateLeçon.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dcDateLeçonPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDate)
                    .addComponent(lblCatV)
                    .addComponent(lblHeures)
                    .addComponent(lblMoniteurs)
                    .addComponent(lblVehicules))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cboMoniteurs, 0, 150, Short.MAX_VALUE)
                            .addComponent(cboVehicules, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(106, 106, 106)
                        .addComponent(btnReserver)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cboCategorieVehicule, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboHeures, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dcDateLeçon, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblReserver, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblReserver, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDate)
                    .addComponent(dcDateLeçon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeures)
                    .addComponent(cboHeures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCatV)
                    .addComponent(cboCategorieVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMoniteurs)
                    .addComponent(cboMoniteurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVehicules)
                            .addComponent(cboVehicules, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(btnReserver)
                        .addGap(20, 20, 20))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        cnx = new ConnexionBDD();
        ctrlV = new CtrlVehicule();
        ctrlM = new CtrlMoniteur();
        ctrlP = new CtrlPlanning();
        
        cboHeures.setEnabled(false);
        
        listeVehicules = ctrlV.findAllVehicles();
        
        ctrlV.loadCategoryNames(cboCategorieVehicule);
        
        // tant que date et type pas séléctionnés -> heure, moniteur et véhicule bloqués et pas remplis
    }//GEN-LAST:event_formWindowOpened

    private void cboCategorieVehiculeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboCategorieVehiculeItemStateChanged
        // TODO add your handling code here:
        cboVehicules.removeAllItems();
        ctrlV.loadVehicleNames(cboVehicules, cboCategorieVehicule.getSelectedIndex(), listeVehicules);
        
        cboMoniteurs.removeAllItems();
        ctrlM.loadInstructorNames(cboMoniteurs, cboCategorieVehicule.getSelectedIndex());
    }//GEN-LAST:event_cboCategorieVehiculeItemStateChanged

    private void dcDateLeçonPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dcDateLeçonPropertyChange
        // TODO add your handling code here:
        /*if(dcDateLeçon.getDate() != null){
            cboHeures.removeAllItems();
            int year = dcDateLeçon.getDate().getYear();
            int month = dcDateLeçon.getDate().getMonth()+1;
            int day = dcDateLeçon.getDate().getDate();
            String strMonth = "";
            String strDay = "";
            if(month < 10){
                strMonth = "0"+String.valueOf(month);
            } else {
                strMonth = String.valueOf(month);
            }
            if(day < 10){
                strDay = "0"+String.valueOf(day);
            } else {
                strDay = String.valueOf(day);
            }
            cboHeures.addItem(String.valueOf(year+1900)+"-"+strMonth+"-"+strDay);
        }*/
        if(!cboHeures.isEnabled()){
            cboHeures.setEnabled(true);
        }
        if(dcDateLeçon.getDate() != null){
            int year = dcDateLeçon.getDate().getYear();
            int month = dcDateLeçon.getDate().getMonth()+1;
            int day = dcDateLeçon.getDate().getDate();
            String strMonth = "";
            String strDay = "";
            if(month < 10){
                strMonth = "0"+String.valueOf(month);
            } else {
                strMonth = String.valueOf(month);
            }
            if(day < 10){
                strDay = "0"+String.valueOf(day);
            } else {
                strDay = String.valueOf(day);
            }
            String strDate = String.valueOf(year+1900)+"-"+String.valueOf(month+1)+"-"+strDay;
            ctrlP.removeOccupiedHours(cboHeures, strDate, cboMoniteurs.getSelectedItem().toString(), cboVehicules.getSelectedItem().toString());
        }
    }//GEN-LAST:event_dcDateLeçonPropertyChange

    private void dcDateLeçonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dcDateLeçonMouseClicked
        // TODO add your handling code here:
        
        /*if(!cboHeures.isEnabled()){
            cboHeures.setEnabled(true);
        }
        if(dcDateLeçon.getDate() != null){
            ctrlP.removeOccupiedHours(cboHeures, dcDateLeçon.getDate(), cboMoniteurs.getSelectedIndex()+1, cboVehicules.getSelectedItem().toString());
        }*/
    }//GEN-LAST:event_dcDateLeçonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmReserverLeçon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmReserverLeçon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmReserverLeçon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmReserverLeçon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmReserverLeçon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReserver;
    private javax.swing.JComboBox<String> cboCategorieVehicule;
    private javax.swing.JComboBox<String> cboHeures;
    private javax.swing.JComboBox<String> cboMoniteurs;
    private javax.swing.JComboBox<String> cboVehicules;
    private com.toedter.calendar.JDateChooser dcDateLeçon;
    private javax.swing.JLabel lblCatV;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblHeures;
    private javax.swing.JLabel lblMoniteurs;
    private javax.swing.JLabel lblReserver;
    private javax.swing.JLabel lblVehicules;
    // End of variables declaration//GEN-END:variables
}
