/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

import Controlers.CtrlLecon;
import Tools.ConnexionBDD;

/**
 *
 * @author Poste de travail
 */
public class FrmStatistiquesEleve extends javax.swing.JFrame {

    private ConnexionBDD cnx;
    private CtrlLecon ctrlL;
    /*private CtrlVehicule ctrlV;
    private CtrlMoniteur ctrlM;
    private CtrlPlanning ctrlP;*/
    
    /**
     * Creates new form FrmStatistiques
     */
    public FrmStatistiquesEleve() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitre = new javax.swing.JLabel();
        lblNbLecons = new javax.swing.JLabel();
        txtNbLecons = new javax.swing.JTextField();
        txtLeconsFinies = new javax.swing.JTextField();
        lblLeconsFinies = new javax.swing.JLabel();
        lblLeconsFutures = new javax.swing.JLabel();
        txtLeconsFutures = new javax.swing.JTextField();
        lblMontantTotal = new javax.swing.JLabel();
        txtMontantTotal = new javax.swing.JTextField();
        lblMontantPasRegle = new javax.swing.JLabel();
        txtMontantPasRegle = new javax.swing.JTextField();
        txtMontantRegle = new javax.swing.JTextField();
        lblMontantRegle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblTitre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitre.setText("Statistiques");

        lblNbLecons.setText("Total de leçons :");

        lblLeconsFinies.setText("Leçons déjà effectuées :");

        lblLeconsFutures.setText("Leçons à faire :");

        lblMontantTotal.setText("Montant total :");

        lblMontantPasRegle.setText("Montant à régler :");

        lblMontantRegle.setText("Montant déjà réglé :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(lblTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNbLecons)
                            .addComponent(lblLeconsFinies)
                            .addComponent(lblLeconsFutures)
                            .addComponent(lblMontantTotal)
                            .addComponent(lblMontantPasRegle)
                            .addComponent(lblMontantRegle))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLeconsFinies, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNbLecons, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLeconsFutures, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMontantTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMontantPasRegle, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMontantRegle, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNbLecons)
                    .addComponent(txtNbLecons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLeconsFinies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLeconsFinies))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLeconsFutures)
                    .addComponent(txtLeconsFutures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMontantTotal)
                    .addComponent(txtMontantTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMontantPasRegle)
                    .addComponent(txtMontantPasRegle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMontantRegle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMontantRegle))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        cnx = new ConnexionBDD();
        ctrlL = new CtrlLecon();
        
        txtNbLecons.setEditable(false);
        txtLeconsFinies.setEditable(false);
        txtLeconsFutures.setEditable(false);
        txtMontantTotal.setEditable(false);
        txtMontantPasRegle.setEditable(false);
        txtMontantRegle.setEditable(false);
        
        txtNbLecons.setText(String.valueOf(ctrlL.findTotalAmountOfLessons(8)));
        txtLeconsFinies.setText(String.valueOf(ctrlL.findAmountOfLessonsDone(8)));
        txtLeconsFutures.setText(String.valueOf(ctrlL.findAmountOfLessonsLeft(8)));
        txtMontantTotal.setText(String.valueOf(ctrlL.findTotalPrice(8))+" €");
        txtMontantPasRegle.setText(String.valueOf(ctrlL.findPriceLeftToPay(8))+" €");
        txtMontantRegle.setText(String.valueOf(ctrlL.findPricePaid(8))+" €");
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmStatistiquesEleve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmStatistiquesEleve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmStatistiquesEleve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmStatistiquesEleve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmStatistiquesEleve().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLeconsFinies;
    private javax.swing.JLabel lblLeconsFutures;
    private javax.swing.JLabel lblMontantPasRegle;
    private javax.swing.JLabel lblMontantRegle;
    private javax.swing.JLabel lblMontantTotal;
    private javax.swing.JLabel lblNbLecons;
    private javax.swing.JLabel lblTitre;
    private javax.swing.JTextField txtLeconsFinies;
    private javax.swing.JTextField txtLeconsFutures;
    private javax.swing.JTextField txtMontantPasRegle;
    private javax.swing.JTextField txtMontantRegle;
    private javax.swing.JTextField txtMontantTotal;
    private javax.swing.JTextField txtNbLecons;
    // End of variables declaration//GEN-END:variables
}
